# CloudFormation GitSync Deployment Configuration
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/git-sync-concepts-terms.html

template-file-path: ./master.yaml

stack-name: ecs-cicd-stack

region: eu-central-1

parameters:
  GithubOrg: eugeneanokye99
  GithubRepo: ecs-cicd-app
  TemplatesBucket: ecs-cloudformation-infra
  TemplatesPrefix: templates
  OIDCProviderArn: arn:aws:iam::120569613427:oidc-provider/token.actions.githubusercontent.com

tags:
  Project: ecs-cicd
  Environment: prod
  Owner: EugeneAnokye
  ManagedBy: CloudFormation-GitSync
