AWSTemplateFormatVersion: '2010-09-09'
Description: ECR stack - container image repository with immutable tags and scan on push

Parameters:
  ProjectName:
    Type: String
    Default: ecs-cicd
  Environment:
    Type: String
    Default: prod

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${ProjectName}-app
      ImageTagMutability: MUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Remove untagged images after 1 day",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 1
                },
                "action": { "type": "expire" }
              }
            ]
          }
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-app
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: EugeneAnokye

Outputs:
  RepositoryUri:
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub ${ProjectName}-ECRRepositoryUri

  RepositoryName:
    Value: !Ref ECRRepository
    Export:
      Name: !Sub ${ProjectName}-ECRRepositoryName

  RepositoryArn:
    Value: !GetAtt ECRRepository.Arn
    Export:
      Name: !Sub ${ProjectName}-ECRRepositoryArn
